export const FETCH_AVAILABLE_BIKES = "FETCH_AVAILABLE_BIKES";
export const FETCH_AVAILABLE_BIKES_SUCCESS = "FETCH_AVAILABLE_BIKES_SUCCESS";
export const FETCH_AVAILABLE_BIKES_ERROR = "FETCH_AVAILABLE_BIKES_ERROR";
export const ADD_BIKE_AVAILABLE_BIKES = "ADD_BIKE_AVAILABLE_BIKES";
export const REMOVE_BIKE_AVAILABLE_BIKES = "REMOVE_BIKE_AVAILABLE_BIKES";
