export const FETCH_RENTED_BIKES = "FETCH_RENTED_BIKES";
export const FETCH_RENTED_BIKES_SUCCESS = "FETCH_RENTED_BIKES_SUCCESS";
export const FETCH_RENTED_BIKES_ERROR = "FETCH_RENTED_BIKES_ERROR";
export const ADD_RENT_RENTED_BIKES = "ADD_RENT_RENTED_BIKES";
export const REMOVE_RENT_RENTED_BIKES = "REMOVE_RENT_RENTED_BIKES";
